name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fpassword:latest .
      - name: publish
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fpassword:latest
